// Script to update all doc pages to use the useMDXContent hook
// This is a reference script - pages should be updated individually

export const docPagesToUpdate = [
  { file: 'ai-assistants/Configuration.tsx', mdxPath: 'ai-assistants/configuration', icon: 'Sliders', title: 'Assistant Configuration', subtitle: 'Advanced configuration options' },
  { file: 'ai-assistants/settings/General.tsx', mdxPath: 'ai-assistants/settings/general', icon: 'Settings', title: 'General Settings', subtitle: 'Configure general assistant settings' },
  { file: 'ai-assistants/settings/PromptAndTools.tsx', mdxPath: 'ai-assistants/settings/prompt-and-tools', icon: 'Wrench', title: 'Prompts & Tools', subtitle: 'Configure prompts and tools' },
  { file: 'ai-assistants/settings/Voice.tsx', mdxPath: 'ai-assistants/settings/voice', icon: 'Mic', title: 'Voice Settings', subtitle: 'Configure voice settings' },
  { file: 'campaigns/Overview.tsx', mdxPath: 'campaigns/overview', icon: 'Megaphone', title: 'Campaigns Overview', subtitle: 'Understanding outbound call campaigns' },
  { file: 'campaigns/Creating.tsx', mdxPath: 'campaigns/creating', icon: 'Plus', title: 'Creating Campaigns', subtitle: 'Step-by-step guide to creating outbound campaigns' },
  { file: 'campaigns/Managing.tsx', mdxPath: 'campaigns/managing', icon: 'Settings2', title: 'Managing Campaigns', subtitle: 'Manage and monitor your campaigns' },
  { file: 'campaigns/BestPractices.tsx', mdxPath: 'campaigns/best-practices', icon: 'Target', title: 'Best Practices', subtitle: 'Best practices for campaign success' },
  { file: 'leads/Managing.tsx', mdxPath: 'leads/managing', icon: 'FolderTree', title: 'Managing Leads', subtitle: 'How to manage leads in Spotzy.ai' },
  { file: 'phone-numbers/Overview.tsx', mdxPath: 'phone-numbers/overview', icon: 'Phone', title: 'Phone Numbers Overview', subtitle: 'Understanding phone numbers in Spotzy.ai' },
  { file: 'phone-numbers/Types.tsx', mdxPath: 'phone-numbers/types', icon: 'List', title: 'Phone Number Types', subtitle: 'Different types of phone numbers' },
  { file: 'phone-numbers/Purchasing.tsx', mdxPath: 'phone-numbers/purchasing', icon: 'ShoppingCart', title: 'Purchasing Numbers', subtitle: 'How to purchase phone numbers' },
  { file: 'phone-numbers/SupportedCountries.tsx', mdxPath: 'phone-numbers/supported-countries', icon: 'Globe', title: 'Supported Countries', subtitle: 'Countries where phone numbers are available' },
  { file: 'inbound-calls/Basics.tsx', mdxPath: 'inbound-calls/basics', icon: 'PhoneIncoming', title: 'Inbound Calls Basics', subtitle: 'Understanding inbound calls' },
  { file: 'inbound-calls/Routing.tsx', mdxPath: 'inbound-calls/routing', icon: 'GitBranch', title: 'Call Routing', subtitle: 'Routing inbound calls' },
  { file: 'inbound-calls/Handling.tsx', mdxPath: 'inbound-calls/handling', icon: 'Headphones', title: 'Call Handling', subtitle: 'Handling inbound calls' },
  { file: 'inbound-calls/Forwarding.tsx', mdxPath: 'inbound-calls/forwarding', icon: 'Share2', title: 'Call Forwarding', subtitle: 'Forwarding inbound calls' },
  { file: 'outbound-calls/Basics.tsx', mdxPath: 'outbound-calls/basics', icon: 'PhoneOutgoing', title: 'Outbound Calls Basics', subtitle: 'Understanding outbound calls' },
  { file: 'outbound-calls/CallerId.tsx', mdxPath: 'outbound-calls/caller-id', icon: 'UserCheck', title: 'Caller ID', subtitle: 'Managing caller ID' },
  { file: 'outbound-calls/Voicemail.tsx', mdxPath: 'outbound-calls/voicemail', icon: 'Voicemail', title: 'Voicemail Handling', subtitle: 'Handling voicemail' },
  { file: 'conversation-design/Prompts.tsx', mdxPath: 'conversation-design/prompts', icon: 'MessageSquare', title: 'Conversation Prompts', subtitle: 'Designing conversation prompts' },
  { file: 'conversation-design/KnowledgeBase.tsx', mdxPath: 'conversation-design/knowledge-base', icon: 'BookOpen', title: 'Knowledge Base', subtitle: 'Building a knowledge base' },
  { file: 'conversation-design/Interruptions.tsx', mdxPath: 'conversation-design/interruptions', icon: 'AlertCircle', title: 'Handling Interruptions', subtitle: 'Managing conversation interruptions' },
  { file: 'conversation-design/Language.tsx', mdxPath: 'conversation-design/language', icon: 'Languages', title: 'Language Settings', subtitle: 'Configuring language settings' },
  { file: 'pricing/Overview.tsx', mdxPath: 'pricing/overview', icon: 'DollarSign', title: 'Pricing Overview', subtitle: 'Understanding Spotzy.ai pricing' },
  { file: 'troubleshooting/CallQuality.tsx', mdxPath: 'troubleshooting/call-quality', icon: 'AlertTriangle', title: 'Call Quality Issues', subtitle: 'Troubleshooting call quality' },
  { file: 'troubleshooting/Campaigns.tsx', mdxPath: 'troubleshooting/campaigns', icon: 'AlertTriangle', title: 'Campaign Issues', subtitle: 'Troubleshooting campaigns' },
  { file: 'troubleshooting/Leads.tsx', mdxPath: 'troubleshooting/leads', icon: 'AlertTriangle', title: 'Lead Issues', subtitle: 'Troubleshooting leads' },
  { file: 'troubleshooting/SetupIssues.tsx', mdxPath: 'troubleshooting/setup-issues', icon: 'AlertTriangle', title: 'Setup Issues', subtitle: 'Troubleshooting setup' },
  { file: 'troubleshooting/GoHighLevel.tsx', mdxPath: 'troubleshooting/gohighlevel', icon: 'AlertTriangle', title: 'GoHighLevel Issues', subtitle: 'Troubleshooting GoHighLevel integration' },
  { file: 'troubleshooting/SipIntegration.tsx', mdxPath: 'troubleshooting/sip-integration', icon: 'AlertTriangle', title: 'SIP Integration Issues', subtitle: 'Troubleshooting SIP integration' },
  { file: 'troubleshooting/VoiceProblems.tsx', mdxPath: 'troubleshooting/voice-problems', icon: 'AlertTriangle', title: 'Voice Problems', subtitle: 'Troubleshooting voice issues' },
];
